/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicDialog: typeof import('./src/components/Dialog/src/basicDialog.vue')['default']
    BasicForm: typeof import('./src/components/Form/src/BasicForm.vue')['default']
    Button: typeof import('./src/components/button/button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Message: typeof import('./src/components/message/message.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NDataTabl: typeof import('naive-ui')['NDataTabl']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMe: typeof import('naive-ui')['NMe']
    NMenu: typeof import('naive-ui')['NMenu']
    NMes: typeof import('naive-ui')['NMes']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    'NMessaproviderge-': typeof import('naive-ui')['NMessaproviderge-']
    NPagination: typeof import('naive-ui')['NPagination']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTimePicker: typeof import('naive-ui')['NTimePicker']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTransfer: typeof import('naive-ui')['NTransfer']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/table/components/search/search.vue')['default']
    Table: typeof import('./src/components/table/table.vue')['default']
  }
}
