/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button/button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Message: typeof import('./src/components/message/message.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDataTabl: typeof import('naive-ui')['NDataTabl']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMe: typeof import('naive-ui')['NMe']
    NMenu: typeof import('naive-ui')['NMenu']
    NMes: typeof import('naive-ui')['NMes']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    'NMessaproviderge-': typeof import('naive-ui')['NMessaproviderge-']
    NPagination: typeof import('naive-ui')['NPagination']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/table/components/search/search.vue')['default']
    Table: typeof import('./src/components/table/table.vue')['default']
  }
}
